version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: arduinoContainer
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: p123456789
      POSTGRES_DB: pastilleroDb
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
